name: Run Agent 1 Daily

on:
  schedule:
    - cron: '0 18 * * *'  # Ejecuta a las 19:00 hora Irlanda (UTC+1 en verano)
  workflow_dispatch:      # También permite ejecutarlo manualmente desde GitHub

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Save credentials.json from GitHub Secret
      run: |
        echo "${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}" > credentials.json

    - name: Run agent 1 script
      run: python agent_1_data_ingestion.py
