name: Agent 3 - Recommender Engine

on:
  schedule:
    - cron: '15 19 * * *'  # Todos los días a las 19:15 UTC (después de Agente 1 y 2)
  workflow_dispatch:       # Permite ejecutarlo manualmente

jobs:
  run-agent3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy gspread oauth2client

      - name: Run Agent 3 - Recommender
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        run: |
          python agent_3/agent_3_main.py
