name: Agent 1 - Multi-Symbol Ingestion

on:
  #schedule:
    #- cron: '0 16 * * *'  # Every day at 16:00 UTC
  workflow_dispatch:     
jobs:
  run-agent1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests gspread oauth2client pandas

      - name: Run Agent 1 Multi-symbol
        env:
          ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
          GOOGLE_SHEETS_CREDENTIALS_MULTI: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS_MULTI }}
        run: |
          python agent_1/agent_1_data_ingestion.py


        

